swagger: "2.0"
info:
  version: "0.0.1"
  title: trader m5 Service
# during dev, should point to your local machine
host: localhost:10030
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: api-key
    
paths:
  /traders:
    # binds a127 app logic to a route
    x-swagger-router-controller: trader.controller
    get:
      security:
        - api_key: []
      description: gets all trader-m5 for a user
      operationId: get
      parameters:
        - name: userId
          description: the owner of the traders
          in: query
          required: true
          type: string
          default: 57b16c90b285f00a0c301318
        - name: _id
          description: the optional trader id
          in: query
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/TraderQuery"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      security:
        - api_key: []
      description: adds a new trader-m5 for a user using the strategy passed
      operationId: create
      parameters:
        - name: payload
          description: the required input for the event to create
          in: body
          required: true
          schema:
            $ref: "#/definitions/TraderEventPayload"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/EventResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  TraderEventPayload:
    type: object
    required:
      - userId
      - strategyId
      - instrument
    properties:
      strategyId:
        type: string
        description: the trader's strategy
        default: 5788751b5ff4760ceb704ec1
      userId:
        type: string
        description: the owner of the trader
        default: 57b16c90b285f00a0c301318
      instrument:
        type: string
        enum:
          - AUD_USD
  TraderQuery:
    type: object
    properties:
      created: 
        type: string
        format: date-time
        description: the date time the trader created
      updated: 
        type: string
        format: date-time
        description: last time the trader updated 
      status: 
        type: string
        enum:
          - Created
          - In
          - Out
        description: the last status of the trader
      version: 
        type: number
        description: the version number of the trader
      instrument: 
        type: string
        enum:
          - AUD_USD
        description: the instrument that the trader is using
      id: 
        type: 
          - string
          - number
        description: the id of the trader
      userId: 
        type: string
        description: the owner of the trader
  EventResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
